### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by RogerRogerUSC** [burlachenkok/flpytorch#9]
@burlachenkok Hi, I am really interested in your project and have established the environment. However, when I ran it, I could not get the result successfully. One of the errors I met showed "ValueError: Cannot take a larger sample than population when 'replace=False'." Do you have any solutions for this?  Thank you!
![1669264799875](https://user-images.githubusercontent.com/118097091/203695674-4760ee48-7df3-4592-92bd-9ad6fede56dc.png)
Configuration: 
![1669264904065](https://user-images.githubusercontent.com/118097091/203695872-b6712243-60fa-47de-84c6-3eb78c3e5b0d.png)
![image](https://user-images.githubusercontent.com/118097091/203695908-cdad2e40-88d8-4a17-ac0d-b7cd3647b757.png)

**Comment by burlachenkok** [comment]
Hello @RogerRogerUSC and thank you for trying the project!

First of all, I suggest to:

1. Configure in GUI your setting
2. Select in GUI Extra->LogWindow (or press hotkey F2 from the main window)
3. Please, after you have configured GUI your setups press into "Black Command Line" (Button-1)
4. If you have no objection to reporting the configuration of your system please report:
  a. Configuration of Your System (Button-2)
  b. Information about the version of PyTorch that you're using (Button-3)

![image](https://user-images.githubusercontent.com/3099251/203701877-247261f7-1cb5-471b-ab3e-cda655ab7f90.png)

**Comment by burlachenkok** [comment]
Dear @RogerRogerUSC  thank you for using the solution.

It seems the error is about the total number of **clients** in the dataset being only 1.

And you're trying to sample more than 1 client, in fact, you sample 10 clients uniformly at random during each round (outer iterations)

Please use the CIFAR10_FL dataset it has a split of datasets across 10 clients.

![image](https://user-images.githubusercontent.com/3099251/203702449-ba71d1de-6d64-47b4-b1b0-85b4f2de6c2a.png)

**Comment by RogerRogerUSC** [comment]
Dear @burlachenkok , thank you for your reply! I just changed the configuration as you instructed, but a new error occurred, so I may still need your help.
![1669268933373](https://user-images.githubusercontent.com/118097091/203704082-00d59974-920d-4f51-8228-586bafcfe1b4.png)

**Comment by burlachenkok** [comment]
Sure!

First of all, I suggest to:

1. Configure GUI your setting
2. Select in GUI Extra->LogWindow (or press hotkey F2 from the main window)
3. Please, after you have configured GUI your setups press into "Black Command Line" (Button-1)
4. If you have no objection to reporting the configuration of your system please report:
  a. Configuration of Your System (Button-2)
  b. Information about the version of PyTorch that you're using (Button-3)

![image](https://user-images.githubusercontent.com/3099251/203709994-1b79d145-1a5f-4b4c-a24b-ab44ca64d823.png)

**Comment by RogerRogerUSC** [comment]
@burlachenkok This is the related configuration and information. 

Job '{simcounter}_job_id_{now}' with algorithm 'FEDAVG' has been sumbitted
# Command line for experiment with job_id=1_job_id_1669273689
python run.py \
--rounds "3000" \
--client-sampling-type "uniform" \
--num-clients-per-round "10" \
--global-lr "0.1" \
--global-optimiser "sgd" \
--global-weight-decay "0.0" \
--number-of-local-iters "1" \
--batch-size "500" \
--local-lr "0.01" \
--local-optimiser "sgd" \
--local-weight-decay "0.0" \
--dataset "cifar10_fl" \
--loss "crossentropy" \
--model "tv_resnet18" \
--use-pretrained \
--train-last-layer \
--metric "top_1_acc" \
--global-regulizer "none" \
--global-regulizer-alpha "0.0" \
--checkpoint-dir "../check_points" \
--do-not-save-eval-checkpoints \
--data-path "../data/" \
--compute-type "fp64" \
--gpu "-1" \
--log-gpu-usage \
--num-workers-train "0" \
--num-workers-test "0" \
--deterministic \
--manual-init-seed "123" \
--manual-runtime-seed "456" \
--group-name "" \
--comment "" \
--hostname "roger-dell" \
--eval-every "100" \
--eval-async-threads "0" \
--save-async-threads "0" \
--threadpool-for-local-opt "0" \
--run-id "1_job_id_1669273689" \
--algorithm "fedavg" \
--algorithm-options "internal_sgd:full-gradient" \
--logfile "../logs/1_log_1669273689.txt" \
--client-compressor "ident:5%" \
--extra-track "full_gradient_norm_train,full_objective_value_train" \
--allow-use-nv-tensorcores \
--initialize-shifts-policy "zero" \
--wandb-key "" \
--wandb-project-name "fl_pytorch_simulation" \
--loglevel "debug" \
--logfilter ".*" \
--out "1_job_id_1669273689.bin"

# ===========================================================
2022-11-23 23:08:19.920696
# ===========================================================
# Command line for currently selected configuration in GUI
python run.py \
--rounds "3000" \
--client-sampling-type "uniform" \
--num-clients-per-round "10" \
--global-lr "0.1" \
--global-optimiser "SGD" \
--global-weight-decay "0.0" \
--number-of-local-iters "1" \
--batch-size "500" \
--local-lr "0.01" \
--local-optimiser "SGD" \
--local-weight-decay "0.0" \
--dataset "cifar10_fl" \
--loss "CROSSENTROPY" \
--model "tv_resnet18" \
--use-pretrained \
--train-last-layer \
--metric "top_1_acc" \
--global-regulizer "none" \
--global-regulizer-alpha "0.0" \
--checkpoint-dir "../check_points" \
--do-not-save-eval-checkpoints \
--data-path "../data/" \
--compute-type "fp64" \
--gpu "-1" \
--log-gpu-usage \
--num-workers-train "0" \
--num-workers-test "0" \
--deterministic \
--manual-init-seed "123" \
--manual-runtime-seed "456" \
--group-name "" \
--comment "" \
--hostname "Roger-Dell" \
--eval-every "100" \
--eval-async-threads "0" \
--save-async-threads "0" \
--threadpool-for-local-opt "0" \
--run-id "{simcounter}_job_id_{now}" \
--algorithm "FEDAVG" \
--algorithm-options "internal_sgd:full-gradient" \
--logfile "../logs/{simcounter}_log_{now}.txt" \
--client-compressor "ident:5%" \
--extra-track "full_gradient_norm_train,full_objective_value_train" \
--allow-use-nv-tensorcores \
--initialize-shifts-policy "zero" \
--wandb-key "" \
--wandb-project-name "fl_pytorch_simulation" \
--loglevel "DEBUG" \
--logfilter ".*" \
--out "current.bin"
# ===========================================================

Release unoccupied cache memory from PyTorch...
Running the garbage collector...
 Done. 0.00 MB was removed from Virtual and Resident memory of interpreter. Current used amount of memory is 642.63 MBytes
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.1 (default, Dec 11 2020, 09:29:25) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 512.78
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.10.0
[pip3] torchvision==0.11.1
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0              16_win64_mkl    conda-forge
[conda] cpuonly                   2.0                           0    pytorch
[conda] cudatoolkit               11.1.1              heb2d755_10    conda-forge
[conda] libblas                   3.9.0              16_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              16_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              16_win64_mkl    conda-forge
[conda] liblapacke                3.9.0              16_win64_mkl    conda-forge
[conda] mkl                       2022.1.0           h6a75c08_874    conda-forge
[conda] mkl-devel                 2022.1.0           h57928b3_875    conda-forge
[conda] mkl-include               2022.1.0           h6a75c08_874    conda-forge
[conda] numpy                     1.23.2           py39h1a62c8c_0    conda-forge
[conda] pytorch                   1.10.0              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchvision               0.11.1                 py39_cpu  [cpuonly]  pytorch

**Comment by RogerRogerUSC** [comment]
Hi @burlachenkok, I was trying different parameters, models and datasets many times, but it kept showing "RuntimeError: expected scalar type Long but found Double." Have you encountered this error before?

**Comment by burlachenkok** [comment]
Dear @RogerRogerUSC . I'm closing the ticket, in case of any problems please reopen it in future.
